name: musicplayer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_smart_dialog: ^2.1.6
  flutter_bloc: ^7.0.1
  bloc: ^7.0.0
  sqflite: ^2.0.0+4
  route_transitions: ^2.0.1 # Add transitions when you push a route
  animated_overflow: ^2.0.0 # When a text is overflowed it's animated
  on_audio_query: ^1.1.3+1 # Query your device for new songs
  just_audio: ^0.9.4 # manage your audio
  audio_service: ^0.18.0
  font_awesome_flutter: ^9.1.0 # A lot of icons
  audio_session: ^0.1.6 # Controll how to interact with other apps
  intl_utils: ^2.4.0 # Set up intl for you
  intl: ^0.17.0 # this will manage different languages
  shared_preferences: ^2.0.7 # Create an app cache
  move_to_background: ^1.0.2 # useful to test background service
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_native_splash: ^1.2.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/database/database.sql
flutter_intl:
  enabled: true
  class_name: S
